name: Release
run-name: Release ${{ github.repository }} - ${{ github.ref }}
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' 
jobs:
  release:
    runs-on: ubuntu-latest
    container: 
      image: rotheross/otobo:latest-11_0
      options: --user 0 --entrypoint ""
    env:
      GIT_STRATEGY: clone
    # OTOBO requires a redis service for build
    services:
      redis: 
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # Steps for building the SOPM-File
    steps:
      # Downloads a copy of the code in your repository before running CI 
      - name: Check out repository code
        uses: actions/checkout@v4.1.0
        with:
          set-safe-directory: true
      # Installing OTOBO inside of the container to use the package tool
      - name: Install OTOBO
        shell: bash
        run: su otobo -c "/opt/otobo_install/entrypoint.sh copy_otobo_next"
      # Set VERSION variable from tag
      - name: Get Version
        shell: bash      
        run: |
             TAG=${{ github.ref }}
             VERSION=${TAG#refs/tags/v}
             echo "VERSION=${VERSION}" >> $GITHUB_ENV      
             echo ${TAG}
             echo ${VERSION}
      # Copy files & Prepare SOPM file
      - name: Prepare project
        shell: bash      
        run: |
            su otobo -c "cp -nrf ./src/* /opt/otobo/"
            SOPMFILE=$(basename $(ls -t ./src/*.sopm | head -n2 ) )
            echo "SOPMFILE=${SOPMFILE}" >> $GITHUB_ENV 
            echo ${SOPMFILE}
            su otobo -c "sed \"s/#VERSION#/${VERSION}/g\" ./src/${SOPMFILE} > /opt/otobo/${SOPMFILE}"
      # build
      - name: Build project
        id: build
        shell: bash      
        run: |
             mkdir ./build
             chmod 777 ./build
             su otobo -c "/opt/otobo/bin/otobo.Console.pl Dev::Package::Build /opt/otobo/${SOPMFILE} ./build"
             OPMFILE=$(basename $(ls -t ./build/*.opm | head -n2 ) )
             echo ::set-output name=ARTIFACT_PATH::./build/${OPMFILE}
             echo ::set-output name=ARTIFACT_NAME::${OPMFILE}
      # release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      # Upload the OPM-Package to the created release
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.build.outputs.ARTIFACT_PATH }}
          asset_name: ${{ steps.build.outputs.ARTIFACT_NAME }}
          asset_content_type: application/xml
